info.app.name=Task Manager
info.app.version=1.0.0
info.app.description=User management application
info.app.java.version=${java.version}

management.endpoints.web.exposure.include=*

management.endpoint.health.show-details=always

server.port=8081
spring.application.name=users-app
